{
    'name': 'Accounts Extended',
    'version': '18.0.1.0.0',
    'category': 'Accounting',
    'description': """ 
        Extended functionality of Accounts for Ekara""",
    'author': 'NITS',
    'website': 'https://www.navabrindsol.com/',
    'depends': [
        'base',
        'account',
        'account_accountant',
        'account_report_budget_extended',
        'analytic',
        'sale',
        # 'l10n_in',
        # 'l10n_in_reports_gstr',
        # 'hr_expense_extended',
        # 'payment',
        'account_budget',
        'multi_level_approval',
        # 'report_xlsx',
        'odoo_print_cheque',
        # 'account_invoice_extract',
        'l10n_in_withholding',

        'multi_level_approval_configuration',
        'res_partner_extended',
        'project_extended',
        'account_check_printing',
        'account_batch_payment',
        'account_asset',

    ],
    'data': [
        'security/ir.model.access.csv',
        'security/res_groups.xml',
        'data/budget_sequence.xml',
        'data/mail_template.xml',
        'data/ir_cron.xml',
        'wizard/account_report_view.xml',
        'wizard/budget_revision_reason_view.xml',
        'wizard/crr_report_view.xml',
        'wizard/cur_report_view.xml',
        'wizard/account_payment_register_views.xml',
        'report/reports.xml',
        # 'report/report_invoice.xml',
        'report/proforma_invoice.xml',
        'report/batch_payment_view.xml',
        'report/tax_invoice.xml',
        'report/tax_invoice_view.xml',
        'report/ekara_print_template.xml',
        'report/ekara_invoice_report.xml',
        'report/payment_mail_template.xml',
        # 'views/res_config_settings.xml',
        'views/account_move.xml',
        'views/account_asset_views.xml',
        'views/account_payment.xml',
        'views/fund_management.xml',
        'views/accounts_subgroup.xml',
        'views/cash_pool.xml',
        'views/cash_requirement_report.xml',
        'views/account_followup.xml',
        'views/menu.xml'
    ],
    'license': 'LGPL-3',
    'installable': True,
    'application': True,

}
