{
    'name': "HR Extended",

    'description': """
        HR Extended Functionality for Ekara
        
    """,
    'category': 'HR',
    'version': '18.0.1.0.0',
    'depends': [
        # 'base',
        # 'documents',
        # 'website',
        # 'mail',
        # 'contacts',
        # 'hr',
        # 'hr_recruitment',
        # 'hr_recruitment_extract',
        # 'hr_contract',
        # 'hr_payroll',
        # 'hr_appraisal',
        # 'account',
        # 'product',
        # 'sale',
        # 'sign',
        # 'project',
        # 'report_xlsx',
        # 'multi_level_approval',
        # 'oi_hr_holidays_attachment',

        'mail',
        'base',
        'hr',
        'survey',
        'hr_payroll',
        'hr_employee_extended',
        'hr_contract_salary',
        'documents',
        'report_xlsx',
        'hr_holidays',
        'hr_appraisal',
        'hr_insurance',
        'website_hr_recruitment',
        'employee_stages'
    ],
    'data': [
        'security/security.xml',
        'security/ir.model.access.csv',
        'report/pre_emp_check_report.xml',
        'report/employee_indent_report.xml',
        'report/salary_breakup_report.xml',
        'report/she_nda_form.xml',
        'report/external_media_communication_declare.xml',
        'report/employee_verification_form.xml',
        'report/criminal_case_report.xml',
        'report/consent_form.xml',
        'report/code_of_conduct.xml',
        'report/appointment_order_form.xml',
        'report/interview_assessment.xml',
        'report/pf_nomination_form.xml',
        'report/appointment_letter_emp.xml',
        'report/cmg_and_gpa_details.xml',
        'report/manpower_budget_sheet.xml',
        'report/nda_intellectual_property_form.xml',
        'report/kra_template.xml',
        'report/joining_doc_report.xml',
        'data/sequence.xml',
        # 'data/job_levels_demo.xml',
        'data/mail_template_data.xml',
        'wizard/mail_activity_schedule_views.xml',
        'wizard/manpower_budget.xml',
        'wizard/salary_jv_wizard.xml',
        'wizard/professional_tax_wizard.xml',
        'views/hr_config.xml',
        'views/recruitment_config.xml',
        'views/employee_indent_view.xml',
        'views/applicant_recruitment_invitation.xml',
        'views/pre_emp_check.xml',
        'views/interview_assessment.xml',
        'views/kra_master.xml',
        'views/manpower_budget.xml',
        'views/join_doc_config.xml',
        'views/joining_documents.xml',
        'views/employee_kra.xml',
        'views/website_apply.xml',
        'views/hr_contract.xml',
        'views/menuitem_rename.xml',
        'views/sign_button.xml',
        # 'views/mail_compose_message.xml',
        'views/hr_employee.xml',
        'views/hr_applicant.xml',
        'views/survey.xml',
        'wizard/balance_leaves.xml',
        'wizard/payroll_report_wizard.xml'
    ],
    'demo': [
        'data/job_levels_demo.xml'
    ],
    'installable': True,
    'application': True,
    'license': 'LGPL-3',
}
