# DRY_RUN = True
# /opt/odoo18/odoo18-server/odoo-bin shell -c /etc/odoo18.conf -d ekara_18_test_6
# exec(open('/opt/odoo18/custom-addons/odooekara-18/update_profit_and_loss_odoo18.py').read())
# Update DRY_RUN = False
# -*- coding: utf-8 -*-
"""
Odoo 18 - Rebuild Profit & Loss report from old working definitions + final metadata.

IMPORTANT:
- This script is based on the old working file you supplied.
- Formulas are preserved from the old working data.
- Final exported line metadata is applied: code, foldable, hide_if_zero,
  groupby, print_on_new_page, computation engine, subformula,
  blank_if_zero and green_on_positive.
- Existing report lines/expressions for the target report are deleted first.
- The final metadata's "According to each type of account" is NOT written as
  date_scope='normal' because Odoo 18 does not have a 'normal' date_scope.
  The old working script's valid date_scope is preserved (strict_range).
- Aggregation formula references are remapped when a code changed in the
  final export (for example OSC/ADV and the Personal & Other Expenses codes).
- Escaped formula references such as SADW\\.balance are normalized to
  SADW.balance.
- The transaction is rolled back automatically on any error.
"""

REPORT_XMLID = "l10n_in_reports.profit_and_loss"
DRY_RUN = False

DATA = [{'name': 'Net Profit',
  'level': 0,
  'code': 'NEP',
  'foldable': False,
  'hide_if_zero': False,
  'groupby': None,
  'print_on_new_page': False,
  'engine': 'aggregation',
  'date_scope': 'strict_range',
  'blank_if_zero': False,
  'green_on_positive': True,
  'formula': '(INC.balance - COS.balance - EXP.balance)',
  'label': 'balance',
  'subformula': None,
  'parent_index': None},
 {'name': 'Income',
  'level': 0,
  'code': 'INC',
  'foldable': False,
  'hide_if_zero': False,
  'groupby': None,
  'print_on_new_page': False,
  'engine': 'aggregation',
  'date_scope': 'strict_range',
  'blank_if_zero': False,
  'green_on_positive': True,
  'formula': 'DI.balance + INDI.balance + INT.balance + D.balance + OIN.balance + RI.balance + RIMS.balance +IFD.balance +CG.balance',
  'label': 'balance',
  'subformula': None,
  'parent_index': None},
 {'name': '40000000 Direct Incomes',
  'level': 3,
  'code': 'DI',
  'foldable': False,
  'hide_if_zero': False,
  'groupby': None,
  'print_on_new_page': False,
  'engine': 'domain',
  'date_scope': 'strict_range',
  'blank_if_zero': False,
  'green_on_positive': True,
  'formula': "[('account_id.group_id.id', 'in', [115,112])]",
  'label': 'balance',
  'subformula': '-sum',
  'parent_index': 1},
 {'name': '50000000 Indirect Incomes',
  'level': 3,
  'code': 'INDI',
  'foldable': False,
  'hide_if_zero': False,
  'groupby': None,
  'print_on_new_page': False,
  'engine': 'domain',
  'date_scope': 'strict_range',
  'blank_if_zero': False,
  'green_on_positive': True,
  'formula': "[('account_id.group_id.id', 'in', [116,123])]",
  'label': 'balance',
  'subformula': '-sum',
  'parent_index': 1},
 {'name': '50010000 Interest',
  'level': 3,
  'code': 'INT',
  'foldable': False,
  'hide_if_zero': False,
  'groupby': None,
  'print_on_new_page': False,
  'engine': 'domain',
  'date_scope': 'strict_range',
  'blank_if_zero': False,
  'green_on_positive': True,
  'formula': "[('account_id.group_id.id', 'in', [117,208,222,271,326])]",
  'label': 'balance',
  'subformula': '-sum',
  'parent_index': 1},
 {'name': '50040000 Capital Gains',
  'level': 3,
  'code': 'CG',
  'foldable': True,
  'hide_if_zero': False,
  'groupby': None,
  'print_on_new_page': False,
  'engine': 'domain',
  'date_scope': 'strict_range',
  'blank_if_zero': False,
  'green_on_positive': True,
  'formula': "[('account_id.group_id.id', 'in', [220,270])]",
  'label': 'balance',
  'subformula': '-sum',
  'parent_index': 1},
 {'name': '50020000 Dividend',
  'level': 3,
  'code': 'D',
  'foldable': False,
  'hide_if_zero': False,
  'groupby': None,
  'print_on_new_page': False,
  'engine': 'domain',
  'date_scope': 'strict_range',
  'blank_if_zero': False,
  'green_on_positive': True,
  'formula': "[('account_id.group_id.id', 'in', [118,225,268])]",
  'label': 'balance',
  'subformula': '-sum',
  'parent_index': 1},
 {'name': '50030000 Other Income',
  'level': 3,
  'code': 'OIN',
  'foldable': False,
  'hide_if_zero': False,
  'groupby': 'account_id',
  'print_on_new_page': False,
  'engine': 'domain',
  'date_scope': 'strict_range',
  'blank_if_zero': False,
  'green_on_positive': True,
  'formula': "[('account_id.group_id.id', 'in', [119,152,224,273])]",
  'label': 'balance',
  'subformula': '-sum',
  'parent_index': 1},
 {'name': 'Gross Profit',
  'level': 3,
  'code': 'GRP',
  'foldable': False,
  'hide_if_zero': False,
  'groupby': None,
  'print_on_new_page': False,
  'engine': 'aggregation',
  'date_scope': 'strict_range',
  'blank_if_zero': False,
  'green_on_positive': True,
  'formula': 'INC.balance - COS.balance',
  'label': 'balance',
  'subformula': None,
  'parent_index': 1},
 {'name': 'Cost of Revenue',
  'level': 5,
  'code': 'COS',
  'foldable': True,
  'hide_if_zero': False,
  'groupby': 'account_id',
  'print_on_new_page': False,
  'engine': 'domain',
  'date_scope': 'strict_range',
  'blank_if_zero': False,
  'green_on_positive': False,
  'formula': "[('account_id.account_type', '=', 'expense_direct_cost')]",
  'label': 'balance',
  'subformula': 'sum',
  'parent_index': 8},
 {'name': '40010000 Rental Income',
  'level': 3,
  'code': 'RI',
  'foldable': True,
  'hide_if_zero': False,
  'groupby': None,
  'print_on_new_page': False,
  'engine': 'domain',
  'date_scope': 'strict_range',
  'blank_if_zero': False,
  'green_on_positive': True,
  'formula': "[('account_id.group_id.id', 'in', [41,221,247,269])]",
  'label': 'balance',
  'subformula': '-sum',
  'parent_index': 1},
 {'name': '50030002-Rental Incomes',
  'level': 3,
  'code': 'RIMS',
  'foldable': True,
  'hide_if_zero': False,
  'groupby': None,
  'print_on_new_page': False,
  'engine': 'domain',
  'date_scope': 'strict_range',
  'blank_if_zero': False,
  'green_on_positive': True,
  'formula': "[('account_id.group_id.id', '=', '156')]",
  'label': 'balance',
  'subformula': '-sum',
  'parent_index': 1},
 {'name': '40020000 Interest - Fixed Deposit',
  'level': 3,
  'code': 'IFD',
  'foldable': True,
  'hide_if_zero': False,
  'groupby': None,
  'print_on_new_page': False,
  'engine': 'domain',
  'date_scope': 'strict_range',
  'blank_if_zero': False,
  'green_on_positive': True,
  'formula': "[('account_id.group_id.id', 'in', [143,223,266,272])]",
  'label': 'balance',
  'subformula': '-sum',
  'parent_index': 1},
 {'name': 'Expenses',
  'level': 3,
  'code': 'EXP',
  'foldable': False,
  'hide_if_zero': False,
  'groupby': None,
  'print_on_new_page': False,
  'engine': 'aggregation',
  'date_scope': 'strict_range',
  'blank_if_zero': False,
  'green_on_positive': False,
  'formula': 'DIEXP.balance + INDEXP.balance',
  'label': 'balance',
  'subformula': None,
  'parent_index': 1},
 {'name': 'Direct Expense',
  'level': 5,
  'code': 'DIEXP',
  'foldable': False,
  'hide_if_zero': False,
  'groupby': None,
  'print_on_new_page': False,
  'engine': 'aggregation',
  'date_scope': 'strict_range',
  'blank_if_zero': False,
  'green_on_positive': True,
  'formula': 'PC.balance + MF.balance',
  'label': 'balance',
  'subformula': None,
  'parent_index': 13},
 {'name': '70210000 Management fee',
  'level': 7,
  'code': 'MF',
  'foldable': False,
  'hide_if_zero': False,
  'groupby': 'account_id',
  'print_on_new_page': False,
  'engine': 'domain',
  'date_scope': 'strict_range',
  'blank_if_zero': False,
  'green_on_positive': True,
  'formula': "[('account_id.group_id.id', 'in', [203])]",
  'label': 'balance',
  'subformula': 'sum',
  'parent_index': 14},
 {'name': '70100000 Personnel Cost',
  'level': 7,
  'code': 'PC',
  'foldable': True,
  'hide_if_zero': False,
  'groupby': None,
  'print_on_new_page': False,
  'engine': 'aggregation',
  'date_scope': 'strict_range',
  'blank_if_zero': False,
  'green_on_positive': True,
  'formula': 'SADW.balance + CT.balance + SW.balance + SRAT.balance',
  'label': 'balance',
  'subformula': None,
  'parent_index': 14},
 {'name': '200138 Gift to Father',
  'level': 9,
  'code': 'GTF',
  'foldable': False,
  'hide_if_zero': False,
  'groupby': None,
  'print_on_new_page': False,
  'engine': 'domain',
  'date_scope': 'strict_range',
  'blank_if_zero': False,
  'green_on_positive': True,
  'formula': "[('account_id.group_id.id', 'in', [201,])]",
  'label': 'balance',
  'subformula': 'sum',
  'parent_index': 16},
 {'name': '70110000 Salaries and Wages',
  'level': 9,
  'code': 'SADW',
  'foldable': True,
  'hide_if_zero': False,
  'groupby': None,
  'print_on_new_page': False,
  'engine': 'domain',
  'date_scope': 'strict_range',
  'blank_if_zero': False,
  'green_on_positive': True,
  'formula': "[('account_id.group_id.id', 'in', [149,100,318])]",
  'label': 'balance',
  'subformula': 'sum',
  'parent_index': 16},
 {'name': '70120000 Contribution to PF, ESI, Etc.',
  'level': 9,
  'code': 'CT',
  'foldable': True,
  'hide_if_zero': False,
  'groupby': None,
  'print_on_new_page': False,
  'engine': 'domain',
  'date_scope': 'strict_range',
  'blank_if_zero': False,
  'green_on_positive': True,
  'formula': "[('account_id.group_id.id', 'in', [25,323])]",
  'label': 'balance',
  'subformula': 'sum',
  'parent_index': 16},
 {'name': '70130000 Staff Welfare',
  'level': 9,
  'code': 'SW',
  'foldable': True,
  'hide_if_zero': False,
  'groupby': None,
  'print_on_new_page': False,
  'engine': 'domain',
  'date_scope': 'strict_range',
  'blank_if_zero': False,
  'green_on_positive': True,
  'formula': "[('account_id.group_id.id', 'in', [22,51,322])]",
  'label': 'balance',
  'subformula': 'sum',
  'parent_index': 16},
 {'name': '70140000 Staff Recruitment and Training',
  'level': 9,
  'code': 'SRAT',
  'foldable': True,
  'hide_if_zero': False,
  'groupby': None,
  'print_on_new_page': False,
  'engine': 'domain',
  'date_scope': 'strict_range',
  'blank_if_zero': False,
  'green_on_positive': True,
  'formula': "[('account_id.group_id.id', '=', '23')]",
  'label': 'balance',
  'subformula': 'sum',
  'parent_index': 16},
 {'name': 'Indirect Expense',
  'level': 7,
  'code': 'INDEXP',
  'foldable': False,
  'hide_if_zero': False,
  'groupby': None,
  'print_on_new_page': False,
  'engine': 'aggregation',
  'date_scope': 'strict_range',
  'blank_if_zero': False,
  'green_on_positive': True,
  'formula': 'AC.balance + SAMC.balance + IDEXPFC.balance + DOE.balance + IRE.balance + POEP.balance + PRT.balance + PDG.balance + '
             'PPMS.balance + PBW.balance',
  'label': 'balance',
  'subformula': None,
  'parent_index': 14},
 {'name': '70600000 Administration Cost',
  'level': 9,
  'code': 'AC',
  'foldable': True,
  'hide_if_zero': False,
  'groupby': None,
  'print_on_new_page': False,
  'engine': 'aggregation',
  'date_scope': 'strict_range',
  'blank_if_zero': False,
  'green_on_positive': True,
  'formula': 'SAH.balance + RAAT.balance + INSU.balance + PAST.balance + CEX.balance + TACO.balance + LAPC.balance + RTA.balance + '
             'GE.balance + RENT.balance +S&S.balance + PF&W.balance',
  'label': 'balance',
  'subformula': None,
  'parent_index': 22},
 {'name': '70610000 Security and Housekeeping',
  'level': 11,
  'code': 'SAH',
  'foldable': True,
  'hide_if_zero': False,
  'groupby': None,
  'print_on_new_page': False,
  'engine': 'domain',
  'date_scope': 'strict_range',
  'blank_if_zero': False,
  'green_on_positive': True,
  'formula': "[('account_id.group_id.id', 'in', [24,308])]",
  'label': 'balance',
  'subformula': 'sum',
  'parent_index': 23},
 {'name': '70640000 Rates and Taxes',
  'level': 11,
  'code': 'RAAT',
  'foldable': True,
  'hide_if_zero': False,
  'groupby': None,
  'print_on_new_page': False,
  'engine': 'domain',
  'date_scope': 'strict_range',
  'blank_if_zero': False,
  'green_on_positive': True,
  'formula': "[('account_id.group_id.id', 'in', [45,46,95,101,150,248,316])]",
  'label': 'balance',
  'subformula': 'sum',
  'parent_index': 23},
 {'name': '70650000 Power, Fuel and Water',
  'level': 11,
  'code': 'PF&W',
  'foldable': True,
  'hide_if_zero': False,
  'groupby': None,
  'print_on_new_page': False,
  'engine': 'domain',
  'date_scope': 'strict_range',
  'blank_if_zero': False,
  'green_on_positive': True,
  'formula': "[('account_id.group_id.id', 'in', [307])]",
  'label': 'balance',
  'subformula': 'sum',
  'parent_index': 23},
 {'name': '70690000  Facility Maintenance',
  'level': 11,
  'code': 'FMT',
  'foldable': True,
  'hide_if_zero': False,
  'groupby': None,
  'print_on_new_page': False,
  'engine': 'domain',
  'date_scope': 'strict_range',
  'blank_if_zero': False,
  'green_on_positive': True,
  'formula': "[('account_id.group_id.id', '=', '43')]",
  'label': 'balance',
  'subformula': 'sum',
  'parent_index': 23},
 {'name': '70700000 Insurance',
  'level': 11,
  'code': 'INSU',
  'foldable': True,
  'hide_if_zero': False,
  'groupby': 'account_id',
  'print_on_new_page': False,
  'engine': 'domain',
  'date_scope': 'strict_range',
  'blank_if_zero': False,
  'green_on_positive': True,
  'formula': "[('account_id.group_id.id', 'in', [54,55,102,210,311])]",
  'label': 'balance',
  'subformula': 'sum',
  'parent_index': 23},
 {'name': '70710000 Printing and Stationery',
  'level': 11,
  'code': 'PAST',
  'foldable': True,
  'hide_if_zero': False,
  'groupby': None,
  'print_on_new_page': False,
  'engine': 'domain',
  'date_scope': 'strict_range',
  'blank_if_zero': False,
  'green_on_positive': True,
  'formula': "[('account_id.group_id.id', 'in', [97,103])]",
  'label': 'balance',
  'subformula': 'sum',
  'parent_index': 23},
 {'name': '70720000 Communication Expenses',
  'level': 11,
  'code': 'CEX',
  'foldable': False,
  'hide_if_zero': False,
  'groupby': None,
  'print_on_new_page': False,
  'engine': 'domain',
  'date_scope': 'strict_range',
  'blank_if_zero': False,
  'green_on_positive': True,
  'formula': "[('account_id.group_id.id', 'in', [48,98,104,312])]",
  'label': 'balance',
  'subformula': 'sum',
  'parent_index': 23},
 {'name': '70730000 Travel and Conveyance',
  'level': 11,
  'code': 'TACO',
  'foldable': True,
  'hide_if_zero': False,
  'groupby': None,
  'print_on_new_page': False,
  'engine': 'domain',
  'date_scope': 'strict_range',
  'blank_if_zero': False,
  'green_on_positive': True,
  'formula': "[('account_id.group_id.id', 'in', [49,99,105,206,313])]",
  'label': 'balance',
  'subformula': 'sum',
  'parent_index': 23},
 {'name': '70630000 Legal and Professional Charges',
  'level': 11,
  'code': 'LAPC',
  'foldable': True,
  'hide_if_zero': False,
  'groupby': None,
  'print_on_new_page': False,
  'engine': 'domain',
  'date_scope': 'strict_range',
  'blank_if_zero': False,
  'green_on_positive': True,
  'formula': "[('account_id.group_id.id', 'in', [50,106,249,314])]",
  'label': 'balance',
  'subformula': 'sum',
  'parent_index': 23},
 {'name': '70750000 Remuneration to Auditors',
  'level': 11,
  'code': 'RTA',
  'foldable': True,
  'hide_if_zero': False,
  'groupby': None,
  'print_on_new_page': False,
  'engine': 'domain',
  'date_scope': 'strict_range',
  'blank_if_zero': False,
  'green_on_positive': True,
  'formula': "[('account_id.group_id.id', 'in' , [107,252])]",
  'label': 'balance',
  'subformula': 'sum',
  'parent_index': 23},
 {'name': '70760000 General Expenses',
  'level': 11,
  'code': 'GE',
  'foldable': True,
  'hide_if_zero': False,
  'groupby': None,
  'print_on_new_page': False,
  'engine': 'domain',
  'date_scope': 'strict_range',
  'blank_if_zero': False,
  'green_on_positive': True,
  'formula': "[('account_id.group_id.id', 'in', [47,108,207,315])]",
  'label': 'balance',
  'subformula': 'sum',
  'parent_index': 23},
 {'name': '70740000 Software subscription',
  'level': 11,
  'code': 'S&S',
  'foldable': False,
  'hide_if_zero': False,
  'groupby': None,
  'print_on_new_page': False,
  'engine': 'domain',
  'date_scope': 'strict_range',
  'blank_if_zero': False,
  'green_on_positive': True,
  'formula': "[('account_id.group_id.id', '=', '250')]",
  'label': 'balance',
  'subformula': 'sum',
  'parent_index': 23},
 {'name': '70770000 Rent',
  'level': 11,
  'code': 'RENT',
  'foldable': True,
  'hide_if_zero': False,
  'groupby': None,
  'print_on_new_page': False,
  'engine': 'domain',
  'date_scope': 'strict_range',
  'blank_if_zero': False,
  'green_on_positive': True,
  'formula': "[('account_id.group_id.id', 'in', [109,306])]",
  'label': 'balance',
  'subformula': 'sum',
  'parent_index': 23},
 {'name': '80000000 Sales and Marketing Cost',
  'level': 9,
  'code': 'SAMC',
  'foldable': True,
  'hide_if_zero': False,
  'groupby': None,
  'print_on_new_page': False,
  'engine': 'aggregation',
  'date_scope': 'strict_range',
  'blank_if_zero': False,
  'green_on_positive': True,
  'formula': 'ADV.balance +OSC.balance',
  'label': 'balance',
  'subformula': None,
  'parent_index': 22},
 {'name': '80100000 Advertisement',
  'level': 11,
  'code': 'ADV',
  'foldable': True,
  'hide_if_zero': False,
  'groupby': None,
  'print_on_new_page': False,
  'engine': 'domain',
  'date_scope': 'strict_range',
  'blank_if_zero': False,
  'green_on_positive': True,
  'formula': "[('account_id.group_id.id', 'in', [325])]",
  'label': 'balance',
  'subformula': 'sum',
  'parent_index': 37},
 {'name': '80300000 Other Selling Costs',
  'level': 11,
  'code': 'OSC',
  'foldable': True,
  'hide_if_zero': False,
  'groupby': None,
  'print_on_new_page': False,
  'engine': 'domain',
  'date_scope': 'strict_range',
  'blank_if_zero': False,
  'green_on_positive': True,
  'formula': "[('account_id.group_id.id', 'in' , [110, 251,324])]",
  'label': 'balance',
  'subformula': 'sum',
  'parent_index': 37},
 {'name': 'Finance Cost',
  'level': 9,
  'code': 'IDEXPFC',
  'foldable': True,
  'hide_if_zero': False,
  'groupby': None,
  'print_on_new_page': False,
  'engine': 'aggregation',
  'date_scope': 'strict_range',
  'blank_if_zero': False,
  'green_on_positive': True,
  'formula': 'FC.balance + DEP.balance + ITFTY.balance +BC.balance',
  'label': 'balance',
  'subformula': None,
  'parent_index': 22},
 {'name': '80600000 Finance Costs',
  'level': 11,
  'code': 'FC',
  'foldable': True,
  'hide_if_zero': False,
  'groupby': None,
  'print_on_new_page': False,
  'engine': 'domain',
  'date_scope': 'strict_range',
  'blank_if_zero': False,
  'green_on_positive': True,
  'formula': "[('account_id.group_id.id', 'in', [4, 44,162])]",
  'label': 'balance',
  'subformula': 'sum',
  'parent_index': 40},
 {'name': '80610000 Bank charges',
  'level': 11,
  'code': 'BC',
  'foldable': True,
  'hide_if_zero': False,
  'groupby': None,
  'print_on_new_page': False,
  'engine': 'domain',
  'date_scope': 'strict_range',
  'blank_if_zero': False,
  'green_on_positive': True,
  'formula': "[('account_id.group_id.id', 'in', [219,317])]",
  'label': 'balance',
  'subformula': 'sum',
  'parent_index': 40},
 {'name': '90000000 Depreciation',
  'level': 11,
  'code': 'DEP',
  'foldable': True,
  'hide_if_zero': False,
  'groupby': None,
  'print_on_new_page': False,
  'engine': 'domain',
  'date_scope': 'strict_range',
  'blank_if_zero': False,
  'green_on_positive': True,
  'formula': "[('account_id.group_id.id', 'in' , [42, 43,111,112, 333])]",
  'label': 'balance',
  'subformula': 'sum',
  'parent_index': 40},
 {'name': '95000000 Income-Tax for the year',
  'level': 11,
  'code': 'ITFTY',
  'foldable': True,
  'hide_if_zero': False,
  'groupby': None,
  'print_on_new_page': False,
  'engine': 'domain',
  'date_scope': 'strict_range',
  'blank_if_zero': False,
  'green_on_positive': True,
  'formula': "[('account_id.group_id.id', 'in' , [209,332])]",
  'label': 'balance',
  'subformula': 'sum',
  'parent_index': 40},
 {'name': '6000-Direct Operating Expenses',
  'level': 9,
  'code': 'DOE',
  'foldable': True,
  'hide_if_zero': False,
  'groupby': None,
  'print_on_new_page': False,
  'engine': 'aggregation',
  'date_scope': 'strict_range',
  'blank_if_zero': False,
  'green_on_positive': True,
  'formula': 'PDOE.balance + SAW.balance + RAMO.balance',
  'label': 'balance',
  'subformula': None,
  'parent_index': 22},
 {'name': '60100000-Purchases/Direct Operating Exp',
  'level': 11,
  'code': 'PDOE',
  'foldable': True,
  'hide_if_zero': False,
  'groupby': None,
  'print_on_new_page': False,
  'engine': 'domain',
  'date_scope': 'strict_range',
  'blank_if_zero': False,
  'green_on_positive': True,
  'formula': "[('account_id.group_id.id', '=', '93')]",
  'label': 'balance',
  'subformula': 'sum',
  'parent_index': 45},
 {'name': '70110000 Salaries and Wages',
  'level': 11,
  'code': 'SAW',
  'foldable': True,
  'hide_if_zero': False,
  'groupby': None,
  'print_on_new_page': False,
  'engine': 'domain',
  'date_scope': 'strict_range',
  'blank_if_zero': False,
  'green_on_positive': True,
  'formula': "[('account_id.group_id.id', '=', '94')]",
  'label': 'balance',
  'subformula': 'sum',
  'parent_index': 45},
 {'name': '70690000-Repairs & Maintenance - Others',
  'level': 11,
  'code': 'RAMO',
  'foldable': True,
  'hide_if_zero': False,
  'groupby': None,
  'print_on_new_page': False,
  'engine': 'domain',
  'date_scope': 'strict_range',
  'blank_if_zero': False,
  'green_on_positive': True,
  'formula': "[('account_id.group_id.id', '=', '96')]",
  'label': 'balance',
  'subformula': 'sum',
  'parent_index': 45},
 {'name': '70610000 Power, Fuel and Water',
  'level': 11,
  'code': 'PFW',
  'foldable': True,
  'hide_if_zero': False,
  'groupby': None,
  'print_on_new_page': False,
  'engine': 'domain',
  'date_scope': 'strict_range',
  'blank_if_zero': False,
  'green_on_positive': True,
  'formula': "[('account_id.group_id.id', '=', '52')]",
  'label': 'balance',
  'subformula': 'sum',
  'parent_index': 45},
 {'name': '70620000 Printing and Stationery',
  'level': 11,
  'code': 'PAS',
  'foldable': True,
  'hide_if_zero': False,
  'groupby': None,
  'print_on_new_page': False,
  'engine': 'domain',
  'date_scope': 'strict_range',
  'blank_if_zero': False,
  'green_on_positive': True,
  'formula': "[('account_id.group_id.id', '=', '53')]",
  'label': 'balance',
  'subformula': 'sum',
  'parent_index': 45},
 {'name': '100100000 Investment Related Expenses',
  'level': 9,
  'code': 'IRE',
  'foldable': True,
  'hide_if_zero': False,
  'groupby': None,
  'print_on_new_page': False,
  'engine': 'aggregation',
  'date_scope': 'strict_range',
  'blank_if_zero': False,
  'green_on_positive': True,
  'formula': 'BCP.balance + DCP.balance + SOEP.balance +B&SC.balance + S&TT.balance +STTP.balance +PIMS.balance',
  'label': 'balance',
  'subformula': None,
  'parent_index': 22},
 {'name': '100100001 Bank Charges',
  'level': 11,
  'code': 'BCP',
  'foldable': True,
  'hide_if_zero': False,
  'groupby': None,
  'print_on_new_page': False,
  'engine': 'domain',
  'date_scope': 'strict_range',
  'blank_if_zero': False,
  'green_on_positive': True,
  'formula': "[('account_id.group_id.id', 'in', [227,274])]",
  'label': 'balance',
  'subformula': 'sum',
  'parent_index': 51},
 {'name': '100100002 Demat Charges',
  'level': 11,
  'code': 'DCP',
  'foldable': True,
  'hide_if_zero': False,
  'groupby': None,
  'print_on_new_page': False,
  'engine': 'domain',
  'date_scope': 'strict_range',
  'blank_if_zero': False,
  'green_on_positive': True,
  'formula': "[('account_id.group_id.id', 'in', [228,285])]",
  'label': 'balance',
  'subformula': 'sum',
  'parent_index': 51},
 {'name': '100100003 Stampduty & Other Expenses - PMS',
  'level': 11,
  'code': 'SOEP',
  'foldable': True,
  'hide_if_zero': False,
  'groupby': None,
  'print_on_new_page': False,
  'engine': 'domain',
  'date_scope': 'strict_range',
  'blank_if_zero': False,
  'green_on_positive': True,
  'formula': "[('account_id.group_id.id', '=', '229')]",
  'label': 'balance',
  'subformula': 'sum',
  'parent_index': 51},
 {'name': '100100004 Brokerage & Service Charges',
  'level': 11,
  'code': 'B&SC',
  'foldable': False,
  'hide_if_zero': False,
  'groupby': None,
  'print_on_new_page': False,
  'engine': 'domain',
  'date_scope': 'strict_range',
  'blank_if_zero': False,
  'green_on_positive': True,
  'formula': "[('account_id.group_id.id', 'in', [276])]",
  'label': 'balance',
  'subformula': 'sum',
  'parent_index': 51},
 {'name': '100100005 Security Transaction Tax',
  'level': 11,
  'code': 'S&TT',
  'foldable': False,
  'hide_if_zero': False,
  'groupby': None,
  'print_on_new_page': False,
  'engine': 'domain',
  'date_scope': 'strict_range',
  'blank_if_zero': False,
  'green_on_positive': True,
  'formula': "[('account_id.group_id.id', 'in', [277])]",
  'label': 'balance',
  'subformula': 'sum',
  'parent_index': 51},
 {'name': '100100006 STT Paid',
  'level': 11,
  'code': 'STTP',
  'foldable': True,
  'hide_if_zero': False,
  'groupby': None,
  'print_on_new_page': False,
  'engine': 'domain',
  'date_scope': 'strict_range',
  'blank_if_zero': False,
  'green_on_positive': True,
  'formula': "[('account_id.group_id.id', 'in', [278])]",
  'label': 'balance',
  'subformula': 'sum',
  'parent_index': 51},
 {'name': '100100007 investment management services',
  'level': 11,
  'code': 'PIMS',
  'foldable': False,
  'hide_if_zero': False,
  'groupby': None,
  'print_on_new_page': False,
  'engine': 'domain',
  'date_scope': 'strict_range',
  'blank_if_zero': False,
  'green_on_positive': True,
  'formula': "[('account_id.group_id.id', 'in', [336])]",
  'label': 'balance',
  'subformula': 'sum',
  'parent_index': 51},
 {'name': '100200000 Personal & Other  Expenses',
  'level': 9,
  'code': 'POEP',
  'foldable': True,
  'hide_if_zero': False,
  'groupby': None,
  'print_on_new_page': False,
  'engine': 'aggregation',
  'date_scope': 'strict_range',
  'blank_if_zero': False,
  'green_on_positive': True,
  'formula': 'PDE.balance + PD.balance + PEE.balance + PHEP.balance + PPC.balance + PRM.balance + PSP.balance + PSC.balance + PRO.balance '
             '+ PDF.balance +EDU.balance + PME.balance + PRP.balance + PV.balance +PCCE.balance +PMC.balance + PTC.balance',
  'label': 'balance',
  'subformula': None,
  'parent_index': 22},
 {'name': '100200001 Dining Expenses',
  'level': 11,
  'code': 'PDE',
  'foldable': False,
  'hide_if_zero': False,
  'groupby': None,
  'print_on_new_page': False,
  'engine': 'domain',
  'date_scope': 'strict_range',
  'blank_if_zero': False,
  'green_on_positive': True,
  'formula': "[('account_id.group_id.id', 'in', [230,279])]",
  'label': 'balance',
  'subformula': 'sum',
  'parent_index': 59},
 {'name': '100200002 Drawings',
  'level': 11,
  'code': 'PD',
  'foldable': False,
  'hide_if_zero': False,
  'groupby': None,
  'print_on_new_page': False,
  'engine': 'domain',
  'date_scope': 'strict_range',
  'blank_if_zero': False,
  'green_on_positive': True,
  'formula': "[('account_id.group_id.id', 'in', [231,280])]",
  'label': 'balance',
  'subformula': 'sum',
  'parent_index': 59},
 {'name': '100200003 Electricity Expenses',
  'level': 11,
  'code': 'PEE',
  'foldable': False,
  'hide_if_zero': False,
  'groupby': None,
  'print_on_new_page': False,
  'engine': 'domain',
  'date_scope': 'strict_range',
  'blank_if_zero': False,
  'green_on_positive': True,
  'formula': "[('account_id.group_id.id', 'in', [246,281])]",
  'label': 'balance',
  'subformula': 'sum',
  'parent_index': 59},
 {'name': '100200004 Household Expenses',
  'level': 11,
  'code': 'PHEP',
  'foldable': True,
  'hide_if_zero': False,
  'groupby': None,
  'print_on_new_page': False,
  'engine': 'domain',
  'date_scope': 'strict_range',
  'blank_if_zero': False,
  'green_on_positive': True,
  'formula': "[('account_id.group_id.id', 'in', [232,282])]",
  'label': 'balance',
  'subformula': 'sum',
  'parent_index': 59},
 {'name': '100200005 Professional Charges',
  'level': 11,
  'code': 'PPC',
  'foldable': True,
  'hide_if_zero': False,
  'groupby': None,
  'print_on_new_page': False,
  'engine': 'domain',
  'date_scope': 'strict_range',
  'blank_if_zero': False,
  'green_on_positive': True,
  'formula': "[('account_id.group_id.id', 'in', [233,283])]",
  'label': 'balance',
  'subformula': 'sum',
  'parent_index': 59},
 {'name': '100200006 Repair and Maintenance',
  'level': 11,
  'code': 'PRM',
  'foldable': True,
  'hide_if_zero': False,
  'groupby': None,
  'print_on_new_page': False,
  'engine': 'domain',
  'date_scope': 'strict_range',
  'blank_if_zero': False,
  'green_on_positive': True,
  'formula': "[('account_id.group_id.id', 'in', [234,284])]",
  'label': 'balance',
  'subformula': 'sum',
  'parent_index': 59},
 {'name': '100200007 Salary Paid',
  'level': 11,
  'code': 'PSP',
  'foldable': True,
  'hide_if_zero': False,
  'groupby': None,
  'print_on_new_page': False,
  'engine': 'domain',
  'date_scope': 'strict_range',
  'blank_if_zero': False,
  'green_on_positive': True,
  'formula': "[('account_id.group_id.id', 'in', [235,286])]",
  'label': 'balance',
  'subformula': 'sum',
  'parent_index': 59},
 {'name': '100200008 Security Charges',
  'level': 11,
  'code': 'PSC',
  'foldable': True,
  'hide_if_zero': False,
  'groupby': None,
  'print_on_new_page': False,
  'engine': 'domain',
  'date_scope': 'strict_range',
  'blank_if_zero': False,
  'green_on_positive': True,
  'formula': "[('account_id.group_id.id', 'in', [236,287])]",
  'label': 'balance',
  'subformula': 'sum',
  'parent_index': 59},
 {'name': '100200009 Round Off',
  'level': 11,
  'code': 'PRO',
  'foldable': True,
  'hide_if_zero': False,
  'groupby': None,
  'print_on_new_page': False,
  'engine': 'domain',
  'date_scope': 'strict_range',
  'blank_if_zero': False,
  'green_on_positive': True,
  'formula': "[('account_id.group_id.id', '=', '237')]",
  'label': 'balance',
  'subformula': 'sum',
  'parent_index': 59},
 {'name': '100200011 Gift',
  'level': 11,
  'code': 'PDF',
  'foldable': True,
  'hide_if_zero': False,
  'groupby': None,
  'print_on_new_page': False,
  'engine': 'domain',
  'date_scope': 'strict_range',
  'blank_if_zero': False,
  'green_on_positive': True,
  'formula': "[('account_id.group_id.id', 'in', [238,288])]",
  'label': 'balance',
  'subformula': 'sum',
  'parent_index': 59},
 {'name': '100200012 Education',
  'level': 11,
  'code': 'EDU',
  'foldable': True,
  'hide_if_zero': False,
  'groupby': None,
  'print_on_new_page': False,
  'engine': 'domain',
  'date_scope': 'strict_range',
  'blank_if_zero': False,
  'green_on_positive': True,
  'formula': "[('account_id.group_id.id', 'in', [294])]",
  'label': 'balance',
  'subformula': 'sum',
  'parent_index': 59},
 {'name': '100200013 Medical Expense',
  'level': 11,
  'code': 'PME',
  'foldable': False,
  'hide_if_zero': False,
  'groupby': None,
  'print_on_new_page': False,
  'engine': 'domain',
  'date_scope': 'strict_range',
  'blank_if_zero': False,
  'green_on_positive': True,
  'formula': "[('account_id.group_id.id', 'in', [295,327])]",
  'label': 'balance',
  'subformula': 'sum',
  'parent_index': 59},
 {'name': '100200014 Rent Paid',
  'level': 11,
  'code': 'PRP',
  'foldable': False,
  'hide_if_zero': False,
  'groupby': None,
  'print_on_new_page': False,
  'engine': 'domain',
  'date_scope': 'strict_range',
  'blank_if_zero': False,
  'green_on_positive': True,
  'formula': "[('account_id.group_id.id', 'in', [296,305])]",
  'label': 'balance',
  'subformula': 'sum',
  'parent_index': 59},
 {'name': '100200015 Vacation',
  'level': 11,
  'code': 'PV',
  'foldable': False,
  'hide_if_zero': False,
  'groupby': None,
  'print_on_new_page': False,
  'engine': 'domain',
  'date_scope': 'strict_range',
  'blank_if_zero': False,
  'green_on_positive': True,
  'formula': "[('account_id.group_id.id', 'in', [299])]",
  'label': 'balance',
  'subformula': 'sum',
  'parent_index': 59},
 {'name': '100200016 Credit Card Expenses',
  'level': 11,
  'code': 'PCCE',
  'foldable': True,
  'hide_if_zero': False,
  'groupby': None,
  'print_on_new_page': False,
  'engine': 'domain',
  'date_scope': 'strict_range',
  'blank_if_zero': False,
  'green_on_positive': True,
  'formula': "[('account_id.group_id.id', 'in', [304])]",
  'label': 'balance',
  'subformula': 'sum',
  'parent_index': 59},
 {'name': '100200017 Maintenance charges',
  'level': 11,
  'code': 'PMC',
  'foldable': False,
  'hide_if_zero': False,
  'groupby': None,
  'print_on_new_page': False,
  'engine': 'domain',
  'date_scope': 'strict_range',
  'blank_if_zero': False,
  'green_on_positive': True,
  'formula': "[('account_id.group_id.id', 'in', [328])]",
  'label': 'balance',
  'subformula': 'sum',
  'parent_index': 59},
 {'name': '100200018 Transportation charges',
  'level': 11,
  'code': 'PTC',
  'foldable': False,
  'hide_if_zero': False,
  'groupby': None,
  'print_on_new_page': False,
  'engine': 'domain',
  'date_scope': 'strict_range',
  'blank_if_zero': False,
  'green_on_positive': True,
  'formula': "[('account_id.group_id.id', 'in', [329])]",
  'label': 'balance',
  'subformula': 'sum',
  'parent_index': 59},
 {'name': '100200019 Vehicle Maintenance',
  'level': 11,
  'code': 'PVM',
  'foldable': False,
  'hide_if_zero': False,
  'groupby': None,
  'print_on_new_page': False,
  'engine': 'domain',
  'date_scope': 'strict_range',
  'blank_if_zero': False,
  'green_on_positive': True,
  'formula': "[('account_id.group_id.id', 'in', [330])]",
  'label': 'balance',
  'subformula': 'sum',
  'parent_index': 59},
 {'name': '100200020 House Keeping Exp',
  'level': 11,
  'code': 'PHKE',
  'foldable': False,
  'hide_if_zero': False,
  'groupby': None,
  'print_on_new_page': False,
  'engine': 'domain',
  'date_scope': 'strict_range',
  'blank_if_zero': False,
  'green_on_positive': True,
  'formula': "[('account_id.group_id.id', 'in', [335])]",
  'label': 'balance',
  'subformula': 'sum',
  'parent_index': 59},
 {'name': '100300000 Rates & Taxes',
  'level': 9,
  'code': 'PRT',
  'foldable': True,
  'hide_if_zero': False,
  'groupby': None,
  'print_on_new_page': False,
  'engine': 'aggregation',
  'date_scope': 'strict_range',
  'blank_if_zero': False,
  'green_on_positive': True,
  'formula': 'PITP.balance + PPT.balance + PPTP.balance + PSTTP.balance + PTDSI.balance',
  'label': 'balance',
  'subformula': None,
  'parent_index': 22},
 {'name': '100300001 Income Tax Paid',
  'level': 11,
  'code': 'PITP',
  'foldable': True,
  'hide_if_zero': False,
  'groupby': None,
  'print_on_new_page': False,
  'engine': 'domain',
  'date_scope': 'strict_range',
  'blank_if_zero': False,
  'green_on_positive': True,
  'formula': "[('account_id.group_id.id', 'in', [240,289])]",
  'label': 'balance',
  'subformula': 'sum',
  'parent_index': 79},
 {'name': '100300002 Professional Tax',
  'level': 11,
  'code': 'PPT',
  'foldable': True,
  'hide_if_zero': False,
  'groupby': None,
  'print_on_new_page': False,
  'engine': 'domain',
  'date_scope': 'strict_range',
  'blank_if_zero': False,
  'green_on_positive': True,
  'formula': "[('account_id.group_id.id', 'in', [241,290])]",
  'label': 'balance',
  'subformula': 'sum',
  'parent_index': 79},
 {'name': '100300003 Property Tax',
  'level': 11,
  'code': 'PPTP',
  'foldable': False,
  'hide_if_zero': False,
  'groupby': None,
  'print_on_new_page': False,
  'engine': 'domain',
  'date_scope': 'strict_range',
  'blank_if_zero': False,
  'green_on_positive': True,
  'formula': "[('account_id.group_id.id', 'in', [242,291])]",
  'label': 'balance',
  'subformula': 'sum',
  'parent_index': 79},
 {'name': '100300004 STT Paid',
  'level': 11,
  'code': 'PSTTP',
  'foldable': True,
  'hide_if_zero': False,
  'groupby': None,
  'print_on_new_page': False,
  'engine': 'domain',
  'date_scope': 'strict_range',
  'blank_if_zero': False,
  'green_on_positive': True,
  'formula': "[('account_id.group_id.id', '=', '243')]",
  'label': 'balance',
  'subformula': 'sum',
  'parent_index': 79},
 {'name': '100300005 TDS - Interest',
  'level': 11,
  'code': 'PTDSI',
  'foldable': True,
  'hide_if_zero': False,
  'groupby': None,
  'print_on_new_page': False,
  'engine': 'domain',
  'date_scope': 'strict_range',
  'blank_if_zero': False,
  'green_on_positive': True,
  'formula': "[('account_id.group_id.id', 'in', [244,292])]",
  'label': 'balance',
  'subformula': 'sum',
  'parent_index': 79},
 {'name': '100400001 Donation - 80G',
  'level': 9,
  'code': 'PDG',
  'foldable': True,
  'hide_if_zero': False,
  'groupby': None,
  'print_on_new_page': False,
  'engine': 'domain',
  'date_scope': 'strict_range',
  'blank_if_zero': False,
  'green_on_positive': True,
  'formula': "[('account_id.group_id.id', 'in', [245,293])]",
  'label': 'balance',
  'subformula': 'sum',
  'parent_index': 22},
 {'name': '100500000 PMS Expenses',
  'level': 9,
  'code': 'PPMS',
  'foldable': False,
  'hide_if_zero': False,
  'groupby': None,
  'print_on_new_page': False,
  'engine': 'aggregation',
  'date_scope': 'strict_range',
  'blank_if_zero': False,
  'green_on_positive': True,
  'formula': 'PCC.balance + PPMSF.balance + RTOPMS.balance',
  'label': 'balance',
  'subformula': None,
  'parent_index': 22},
 {'name': '100500001 Custodian Charges',
  'level': 11,
  'code': 'PCC',
  'foldable': False,
  'hide_if_zero': False,
  'groupby': None,
  'print_on_new_page': False,
  'engine': 'domain',
  'date_scope': 'strict_range',
  'blank_if_zero': False,
  'green_on_positive': True,
  'formula': "[('account_id.group_id.id', 'in', [301])]",
  'label': 'balance',
  'subformula': 'sum',
  'parent_index': 86},
 {'name': '100500002 PMS Fees',
  'level': 11,
  'code': 'PPMSF',
  'foldable': False,
  'hide_if_zero': False,
  'groupby': None,
  'print_on_new_page': False,
  'engine': 'domain',
  'date_scope': 'strict_range',
  'blank_if_zero': False,
  'green_on_positive': True,
  'formula': "[('account_id.group_id.id', 'in', [302])]",
  'label': 'balance',
  'subformula': 'sum',
  'parent_index': 86},
 {'name': '100500003 Rates and Taxes Others - PMS',
  'level': 11,
  'code': 'RTOPMS',
  'foldable': False,
  'hide_if_zero': False,
  'groupby': None,
  'print_on_new_page': False,
  'engine': 'domain',
  'date_scope': 'strict_range',
  'blank_if_zero': False,
  'green_on_positive': True,
  'formula': "[('account_id.group_id.id', 'in', [303])]",
  'label': 'balance',
  'subformula': 'sum',
  'parent_index': 86},
 {'name': '100600000 Balance writeoff',
  'level': 9,
  'code': 'PBW',
  'foldable': False,
  'hide_if_zero': False,
  'groupby': None,
  'print_on_new_page': False,
  'engine': 'domain',
  'date_scope': 'strict_range',
  'blank_if_zero': False,
  'green_on_positive': True,
  'formula': "[('account_id.group_id.id', 'in', [331])]",
  'label': 'balance',
  'subformula': 'sum',
  'parent_index': 22}]


def clean_formula(formula):
    return (formula or "").replace("\\.", ".")


def validate_metadata(env):
    import re

    available_codes = {r["code"] for r in DATA if r.get("code")}

    duplicate_codes = sorted(
        code for code in available_codes
        if sum(1 for row in DATA if row.get("code") == code) > 1
    )
    if duplicate_codes:
        raise RuntimeError("Duplicate report line codes: %s" % duplicate_codes)

    if len(DATA) != 91:
        raise RuntimeError("Expected 91 metadata rows, found %s" % len(DATA))

    valid_engines = {"domain", "aggregation"}
    valid_date_scopes = {
        "from_beginning",
        "from_fiscalyear",
        "to_beginning_of_fiscalyear",
        "to_beginning_of_period",
        "strict_range",
        "previous_return_period",
    }

    for row in DATA:
        if row["engine"] not in valid_engines:
            raise RuntimeError(
                "Unsupported engine %r on %s" % (row["engine"], row["name"])
            )

        if row["date_scope"] not in valid_date_scopes:
            raise RuntimeError(
                "Unsupported Odoo 18 date_scope %r on %s"
                % (row["date_scope"], row["name"])
            )

        if row["engine"] == "domain" and not row.get("subformula"):
            raise RuntimeError(
                "Domain expression requires a subformula on %s" % row["name"]
            )

        if row.get("groupby") and row["engine"] == "aggregation":
            raise RuntimeError(
                "Aggregation expression cannot use groupby on %s"
                % row["name"]
            )

    # Validate every aggregation reference before touching the database.
    for row in DATA:
        if row["engine"] != "aggregation":
            continue

        formula = clean_formula(row.get("formula"))
        refs = re.findall(
            r"(?<![A-Za-z0-9_])([A-Za-z][A-Za-z0-9_&]*)\.balance\\b",
            formula,
        )
        missing = sorted(set(refs) - available_codes)
        if missing:
            raise RuntimeError(
                "Aggregation line %s references missing codes: %s"
                % (row["name"], missing)
            )


def main(env):
    report = env.ref(REPORT_XMLID)

    if report._name != "account.report":
        raise RuntimeError(
            "%s resolved to %s instead of account.report"
            % (REPORT_XMLID, report._name)
        )

    Line = env["account.report.line"]
    Expr = env["account.report.expression"]

    print("\n" + "=" * 100)
    print("REBUILD ODOO 18 PROFIT & LOSS")
    print("=" * 100)
    print("Report : %s (id=%s)" % (report.display_name, report.id))
    print("Rows   : %s" % len(DATA))
    print("Dry run: %s" % DRY_RUN)

    validate_metadata(env)

    existing_lines = Line.search([("report_id", "=", report.id)])
    existing_exprs = Expr.search(
        [("report_line_id.report_id", "=", report.id)]
    )

    print("Existing lines       : %s" % len(existing_lines))
    print("Existing expressions : %s" % len(existing_exprs))

    if DRY_RUN:
        print("\nDRY RUN - no database changes will be made.")
        print(
            "Would delete %s lines and %s expressions, then recreate %s rows."
            % (len(existing_lines), len(existing_exprs), len(DATA))
        )
        return

    # ------------------------------------------------------------------
    # 1. Delete existing expressions and lines.
    # ------------------------------------------------------------------
    if existing_exprs:
        count = len(existing_exprs)
        existing_exprs.unlink()
        env.cr.flush()
        print("Deleted expressions: %s" % count)

    if existing_lines:
        count = len(existing_lines)
        existing_lines.unlink()
        env.cr.flush()
        print("Deleted lines: %s" % count)

    # ------------------------------------------------------------------
    # 2. Create report lines in metadata order.
    # ------------------------------------------------------------------
    created = []

    for idx, row in enumerate(DATA):
        vals = {
            "name": row["name"],
            "report_id": report.id,
            "sequence": (idx + 1) * 10,
            "foldable": row["foldable"],
            "hide_if_zero": row["hide_if_zero"],
            "print_on_new_page": row["print_on_new_page"],
        }

        if row.get("code"):
            vals["code"] = row["code"]

        if row.get("groupby"):
            vals["groupby"] = row["groupby"]

        parent_index = row.get("parent_index")
        if parent_index is not None:
            if parent_index >= len(created):
                raise RuntimeError(
                    "Invalid parent_index %s on %s"
                    % (parent_index, row["name"])
                )
            vals["parent_id"] = created[parent_index].id

        line = Line.create(vals)
        created.append(line)

    env.cr.flush()
    print("Created report lines: %s" % len(created))

    # ------------------------------------------------------------------
    # 3. Create expressions.
    # ------------------------------------------------------------------
    for line, row in zip(created, DATA):
        expr_vals = {
            "report_line_id": line.id,
            "label": row["label"] or "balance",
            "engine": row["engine"],
            "formula": clean_formula(row["formula"]),
            "date_scope": row["date_scope"],
            "blank_if_zero": row["blank_if_zero"],
            "green_on_positive": row["green_on_positive"],
        }

        if row["engine"] == "domain":
            expr_vals["subformula"] = row["subformula"]
        elif row.get("subformula"):
            expr_vals["subformula"] = row["subformula"]

        Expr.create(expr_vals)

    env.cr.flush()
    print("Created expressions: %s" % len(created))

    # ------------------------------------------------------------------
    # 4. Verification.
    # ------------------------------------------------------------------
    new_lines = Line.search([("report_id", "=", report.id)])
    new_exprs = Expr.search(
        [("report_line_id.report_id", "=", report.id)]
    )

    if len(new_lines) != len(DATA):
        raise RuntimeError(
            "Line verification failed: expected %s, got %s"
            % (len(DATA), len(new_lines))
        )

    if len(new_exprs) != len(DATA):
        raise RuntimeError(
            "Expression verification failed: expected %s, got %s"
            % (len(DATA), len(new_exprs))
        )

    codes = set(new_lines.mapped("code"))
    expected_codes = {r["code"] for r in DATA if r.get("code")}
    if codes != expected_codes:
        raise RuntimeError(
            "Code verification failed. Expected %s, got %s"
            % (sorted(expected_codes), sorted(codes))
        )

    escaped = new_exprs.filtered(
        lambda e: "\\\\." in (e.formula or "")
    )
    if escaped:
        raise RuntimeError(
            "Escaped '.balance' references remain: %s"
            % ", ".join(escaped.mapped("display_name"))
        )

    # Verify metadata fields against the supplied final export.
    for line, row in zip(created, DATA):
        if line.code != row.get("code"):
            raise RuntimeError(
                "Code mismatch on %s: %r != %r"
                % (row["name"], line.code, row.get("code"))
            )

        if line.foldable != row["foldable"]:
            raise RuntimeError("Foldable mismatch on %s" % row["name"])

        if line.hide_if_zero != row["hide_if_zero"]:
            raise RuntimeError("Hide-if-zero mismatch on %s" % row["name"])

        if line.print_on_new_page != row["print_on_new_page"]:
            raise RuntimeError(
                "Print-on-new-page mismatch on %s" % row["name"]
            )

        if (line.groupby or False) != (row["groupby"] or False):
            raise RuntimeError("Group By mismatch on %s" % row["name"])

        expression = line.expression_ids.filtered(
            lambda e: e.label == row["label"]
        )
        if len(expression) != 1:
            raise RuntimeError(
                "Expected exactly one balance expression on %s"
                % row["name"]
            )

        expression = expression[0]

        if expression.engine != row["engine"]:
            raise RuntimeError("Engine mismatch on %s" % row["name"])

        if expression.date_scope != row["date_scope"]:
            raise RuntimeError("Date scope mismatch on %s" % row["name"])

        if expression.formula != clean_formula(row["formula"]):
            raise RuntimeError("Formula mismatch on %s" % row["name"])

        expected_subformula = row.get("subformula")

        if expected_subformula:
            if expression.subformula != expected_subformula:
                raise RuntimeError(
                    "Subformula mismatch on %s: expected %r, got %r"
                    % (
                        row["name"],
                        expected_subformula,
                        expression.subformula,
                    )
                )

        if expression.blank_if_zero != row["blank_if_zero"]:
            raise RuntimeError("Blank-if-zero mismatch on %s" % row["name"])

        if expression.green_on_positive != row["green_on_positive"]:
            raise RuntimeError(
                "Growth-positive mismatch on %s" % row["name"]
            )

    # ------------------------------------------------------------------
    # 5. Commit only after all verification passes.
    # ------------------------------------------------------------------
    env.cr.commit()

    print("\n" + "=" * 100)
    print("SUCCESS - PROFIT & LOSS REBUILT AND COMMITTED")
    print("=" * 100)
    print("Report lines : %s" % len(new_lines))
    print("Expressions  : %s" % len(new_exprs))
    print("Status       : COMMITTED")


try:
    main(env)
except Exception:
    env.cr.rollback()
    print("\nROLLBACK - no changes were committed.")
    raise
