{
    'name': 'Hr Holiday extended',
    'version': '18.0.1.0.0',
    'summary': """Hr Holiday extended for module access.""",
    'description': """Hr Holiday extended for module access""",
    'category': 'Hr Holiday extended for module access',
    'author': 'NITS',
    'live_test_url': 'https://youtu.be/OBwVroUPspw',
    'maintainer': 'NITS',
    'company': 'nits',
    'website': 'https://www.openhrms.com',
    'depends': [
        'base',
        'hr',
        'hr_holidays',
        'hr_payroll_holidays',
    ],
    'data': [
        'security/ir.model.access.csv',
        'security/security.xml',
        'view/hr_holiday.xml',
        'view/hr_leave_sub_type.xml',
              ],
    'images': ['static/description/banner.jpg'],
    'license': 'LGPL-3',
    'installable': True,
    'auto_install': False,
    'application': False,
}
